# Generated by Django 4.0.6 on 2022-08-03 19:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0005_alter_studentprofessionaldetails_honor_and_more'),
        ('staffs', '0003_alter_staffprofessionaldetails_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='SigmaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofessionaldetails', to_field='bennett_email')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staffprofessionaldetails', to_field='bennett_email')),
            ],
        ),
    ]
