# Generated by Django 4.0.6 on 2022-08-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sigmaCoinTransactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sigmatransaction',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
