# Generated by Django 4.0.6 on 2022-08-03 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0004_alter_studentprofessionaldetails_honor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentCoinDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha_coin', models.PositiveBigIntegerField()),
                ('sigma_coin', models.PositiveBigIntegerField()),
                ('xp', models.PositiveIntegerField()),
                ('level', models.PositiveBigIntegerField()),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('student_professional_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofessionaldetails')),
            ],
        ),
    ]
