# Generated by Django 4.0.6 on 2022-08-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentsCoin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentcoindetail',
            name='student_professional_detail_id',
        ),
    ]
