# Generated by Django 4.0.6 on 2022-08-03 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_studentprofessionaldetails_honor_and_more'),
        ('studentsCoin', '0002_remove_studentcoindetail_student_professional_detail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentcoindetail',
            name='student_professional_detail_id',
            field=models.ForeignKey(default='no_email', on_delete=django.db.models.deletion.CASCADE, to='students.studentprofessionaldetails', to_field='bennett_email'),
            preserve_default=False,
        ),
    ]
