# Generated by Django 4.0.6 on 2022-07-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bennett_email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('enrollment_number', models.CharField(max_length=255, unique=True)),
                ('school_code', models.CharField(blank=True, max_length=255, null=True)),
                ('department_code', models.CharField(blank=True, max_length=255, null=True)),
                ('scholarship_percentage', models.PositiveSmallIntegerField(default=0, null=True)),
                ('minor', models.CharField(choices=[('PH', 'Physics'), ('MA', 'Mathematics')], max_length=255, null=True)),
                ('honor', models.CharField(choices=[('PH', 'Physics'), ('MA', 'Mathematics')], max_length=255, null=True)),
                ('batch', models.CharField(blank=True, max_length=255, null=True)),
                ('program', models.CharField(blank=True, max_length=255, null=True)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
                ('admission_date', models.DateField(null=True)),
                ('current_semester', models.SmallIntegerField(default=1)),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('status_change_date', models.DateTimeField(blank=True, null=True)),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
