# Generated by Django 4.0.6 on 2022-09-18 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_studentprofessionaldetails_honor_and_more'),
        ('staffs', '0005_alter_staffprofessionaldetails_designation'),
        ('alphaCoinTransactions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlphaRequestTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('message', models.CharField(max_length=255)),
                ('is_valid', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('receiver_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentprofessionaldetails', to_field='bennett_email')),
                ('sender_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staffprofessionaldetails', to_field='bennett_email')),
            ],
        ),
    ]
