# Generated by Django 4.0.6 on 2022-09-18 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alphaCoinTransactions', '0002_alpharequesttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alpharequesttransaction',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='alpharequesttransaction',
            name='file',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
