# Generated by Django 4.0.6 on 2022-08-03 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staffs', '0002_alter_staffprofessionaldetails_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffCoinDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigma_coin', models.PositiveBigIntegerField()),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
                ('staff_professional_detail_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffs.staffprofessionaldetails', to_field='bennett_email')),
            ],
        ),
    ]
