# Generated by Django 4.0.6 on 2022-08-02 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bennett_email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty_id', models.IntegerField(unique=True)),
                ('designation', models.CharField(choices=[('CS', 'Computer Science'), ('MA', 'Mathematics')], max_length=255)),
                ('cabin_number', models.CharField(blank=True, max_length=255, null=True)),
                ('intercom', models.CharField(blank=True, max_length=15, null=True)),
                ('school_code', models.CharField(max_length=255)),
                ('department_code', models.CharField(max_length=255)),
                ('phd_date', models.DateField(blank=True, null=True)),
                ('phd_institution', models.CharField(max_length=255)),
                ('favourite_courses', models.TextField(blank=True, null=True)),
                ('batch_mentor', models.CharField(max_length=255)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('MA', 'Mathematics'), ('PH', 'Physics')], default='ACTIVE', max_length=255)),
                ('current_timestamp', models.DateTimeField(blank=True, editable=False, null=True)),
            ],
        ),
    ]
