# Generated by Django 4.0.6 on 2022-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofessionaldetails',
            name='status',
            field=models.CharField(choices=[('PH', 'Physics'), ('MA', 'Mathematics')], default='ACTIVE', max_length=255),
        ),
    ]
