# Generated by Django 4.0.6 on 2022-08-08 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0003_alter_staffprofessionaldetails_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofessionaldetails',
            name='designation',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MA', 'Mathematics')], max_length=255),
        ),
    ]
