# Generated by Django 4.0.6 on 2022-09-18 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0004_alter_staffprofessionaldetails_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofessionaldetails',
            name='designation',
            field=models.CharField(choices=[('MA', 'Mathematics'), ('CS', 'Computer Science')], max_length=255),
        ),
    ]
