# Generated by Django 4.0.6 on 2022-10-17 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffs', '0005_alter_staffprofessionaldetails_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofessionaldetails',
            name='designation',
            field=models.CharField(choices=[('CS', 'Computer Science'), ('MA', 'Mathematics')], max_length=255),
        ),
    ]
